export const Positions = [
  'Abastecimiento y Logística',
  'Administración, Contabilidad y Finanzas',
  'Aduana y Comercio Exterior',
  'Atencion al Cliente, Call Center y Telemarketing',
  'Comercial, Ventas y Negocios',
  'Comunicación, Relaciones Institucionales y Públicas',
  'Diseño',
  'Educación, Docencia e Investigación',
  'Enfermería',
  'Gastronomía y Turismo',
  'Gerencia y Dirección General',
  'Ingeniería Civil y Construcción',
  'Ingenierías',
  'Jóvenes Profesionales',
  'Legales',
  'Marketing y Publicidad',
  'Minería, Petróleo y Gas',
  'Oficios y Otros',
  'Pasantía / Trainee',
  'Recursos Humanos y Capacitación',
  'Salud, Medicina y Farmacia',
  'Secretarías y Recepción',
  'Seguros',
  'Tecnología, Sistemas y Telecomunicaciones',
];
